#!/bin/sh
set -e
/usr/sbin/setcap cap_net_bind_service=+ep /home/tavrn/tavrn/tavrn
ln -sfn /home/tavrn/tavrn/tavrn        /usr/local/bin/tavrn
/usr/bin/systemctl restart tavrn
/usr/bin/systemctl --no-pager --lines=0 is-active tavrn
